Patch document
UAlbertaCompEClub/compe-plus pull request #163
Opened 2021-07-18 04:19 UTC by calebschoepp

# Overview

What is the high-level goal of this PR? Is there any important context we should have?

# Changes

List the changes you've made.

# Questions & Notes

Are there any open questions? Anything else important we should know?

# Issue tracking

List any relevant work that still needs to be done. Open and link to issues for them if applicable.

Does this close any tasks?

# Testing & Demo

How did you test these changes? How can the reviewer test these changes?

If the changes are to the UI show screenshots, GIFs, and/or videos.

2021-07-26 15:59 UTC, cyrusdiego approved these changes
LGTM! Sorry for the delay in reviewing this, great work :D

2021-07-26 23:59 UTC, armiantos requested changes
LGTM! Just left a couple nits. And just to confirm, we're not implementing transactional updates on note and document right?

2021-07-26 23:59 UTC, armiantos commented on api/src/controllers/validation.test.ts
> +describe('beAValidUser helper', () => {
Nit
```suggestion
describe('beAValidDocument helper', () => {
```

2021-07-26 23:59 UTC, armiantos commented on api/src/controllers/validation.test.ts
> +    it('does not throw if resume review exists', async () => {
```suggestion
    it('does not throw if document exists', async () => {
```

2021-07-26 23:59 UTC, armiantos commented on api/src/controllers/validation.test.ts
> +    it('throws if resume review does not exist', async () => {
```suggestion
    it('throws if document does not exist', async () => {
```

2021-07-27 03:06 UTC, calebschoepp commented
> LGTM! Just left a couple nits. And just to confirm, we're not implementing transactional updates on note and document right?

That is correct. I felt it wasn't necessary. If one of the two operations fails we will let them know and they can just call the endpoint again since it is idempotent.

2021-07-27 03:24 UTC, armiantos approved these changes
LGTM! Great job 💯

2021-07-27 03:28 UTC, merged