Armi/cors
UAlbertaCompEClub/compe-plus pull request #175
Opened 2021-08-04 23:50 UTC by armiantos

# Overview

* Specify allowed origins header

# Changes

* Configure `cors` as mentioned in [Configuring CORS w/ Dynamic Origin](https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin)

# Questions & Notes

* Do we want to fail a request if it doesn't have the origin tag? Cors wasn't designed for security so I personally think it should not throw an error

# Issue tracking

Closes #65

# Testing & Demo

Refer to unit tests

2021-08-06 06:00 UTC, calebschoepp requested changes
I agree that origin should not be required.

Maybe file a ticket to support preview urls with cors.

Thanks for doing this.

2021-08-06 18:31 UTC, armiantos commented on api/src/controllers/middleware.test.ts
> +    const corsMiddleware = cors({
Agreed, I'll move it over

2021-08-06 18:31 UTC, armiantos commented on api/src/server.ts
> +    }),
Yes!

2021-08-06 18:37 UTC, armiantos commented
Filed #176 to support url wildcards

2021-08-06 20:45 UTC, armiantos commented on api/src/controllers/middleware.test.ts
> +    const corsMiddleware = cors({
Moved, let me know if there's anything else I should update

2021-08-07 01:46 UTC, calebschoepp approved these changes
LGTM! :ship: :smile:

2021-08-07 01:55 UTC, merged