Write calendly endpoints
UAlbertaCompEClub/compe-plus pull request #221
Opened 2021-09-03 22:05 UTC by calebschoepp

# Overview

Endpoints to interact with calendly resource. Note that to speed up the implementation I didn't differentiate between my/any endpoints. Nothing particularly confidential about it anyways.

# Changes

- POST endpoint
- GET endpoint
- PATCH endpoint

# Questions & Notes

- Next PR is going to add authorization.
- I skipped testing for speed of implementation
- Dependent on schema migration PR #220

2021-09-03 23:19 UTC, cyrusdiego approved these changes
This LGTM! Just left some comments, other than that I think it's good.

2021-09-03 23:19 UTC, cyrusdiego commented on api/db/migrations/003_add_calendly_resource.down.sql
> +DROP TABLE IF EXISTS calendlys;
nit: newline

2021-09-03 23:19 UTC, cyrusdiego commented on api/src/repositories/calendlyRepository.ts
> +    console.log(db.update('calendlys', colOptions, where).compile());
is this console log necessary?

2021-09-04 03:16 UTC, armiantos requested changes
Blocking because this will change according with changes in #202 as discussed offline

2021-09-06 21:03 UTC, armiantos approved these changes
LGTM! Let's get this shipped (after adding authorization to calendly routes hahahahha) 🚀

I'm guessing we'll need to implement some sort of queue and run the matching program on our server as a job instead of having the clients patch the calendly object to avoid race conditions.

2021-09-06 22:57 UTC, calebschoepp commented
> LGTM! Let's get this shipped (after adding authorization to calendly routes hahahahha) 
> 
> I'm guessing we'll need to implement some sort of queue and run the matching program on our server as a job instead of having the clients patch the calendly object to avoid race conditions.

Going to merge now. Auth will come in follow up PR.

Matching will be done as a one time thing by us. We can write some sort of sql/ts script to do the job for us.

2021-09-06 23:01 UTC, merged